### ISSUE TITLE
css output is being truncated

### ISSUE THREAD

**Issue by raystrach** [promatik/PHP-JS-CSS-Minifier#5]
hello, thanks for your code, and its not strictly an issue for your code, but i am getting desperate.

the css minifier had been working perfectly, then, out of the blue, it has started to truncate the output to around 3.85kb (regardless of input file size or content)

i was wondering if you had any inkling on what may be causing this.

i do regular yum updates of the server which is the only thing that has changed. i have tested and it has nothing to do with any characters in the input which may have broken the code.

have searched extensively for a solution for a number of hours and tried a number of things for myself and came up with a blank.

EDIT!! after trying for a few more hours, it seems that once the input file moves over 30.8kb it truncates the output. always to around 3.85kb. will keep trying.
cheers - rs

**Comment by promatik** [comment]
Since this is now hosted on Toptal I believe this is no longer an issue, I'll close this for now, please re-open if you still have any problems with it.
