### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by neerajprashar** [promatik/PHP-JS-CSS-Minifier#7]
Hi there, I am getting `PHP Warning:  file_get_contents(https://javascript-minifier.com/raw): failed to open stream: HTTP request failed! HTTP/1.1 413 Request Entity Too Large` error while minifying js file, could you please help?

**Comment by promatik** [comment]
Since this is now hosted on Toptal I believe this is no longer an issue, I'll close this for now 🙌
