### ISSUE TITLE
Offline error 503 API http://javascript-minifier.com/raw

### ISSUE THREAD

**Issue by jucemarvaccaro** [promatik/PHP-JS-CSS-Minifier#8]
Hi, http://javascript-minifier.com/raw offine? 
Is it unstable in maintenance?
file_get_contents(http://javascript-minifier.com/raw): failed to open stream: HTTP request failed!

**Comment by promatik** [comment]
@jucemarvaccaro I think it's a temporary error. It looks like it's back online.

Edit: It's back offline, sure it's in some kind of maintenance, let's hope it to be quick.

**Comment by jucemarvaccaro** [comment]
it's offline yeat! http://javascript-minifier.com/raw 
500 Internal Server Error
nginx/1.10.3 (Ubuntu)

**Comment by promatik** [comment]
Since this is now hosted on Toptal I believe this issues will happen fewer times, probably and hopefully never 🙌
I'm going to close this for now.
