### ISSUE TITLE
toptal.com broke your script!

### ISSUE THREAD

**Issue by dankirshner** [promatik/PHP-JS-CSS-Minifier#9]
The js minimizer, for example, is now here: https://www.toptal.com/developers/javascript-minifier/

But posting to .../raw doesn't work.  They have a "raw" button that seemed to work.  Haven't deciphered it yet...

Thanks,

--Dan

**Comment by jodosha** [comment]
Hello, I'm a backend architect at Toptal.

We're sorry about the problem that we caused during the transition to our infrastructure.
We took remediation steps and prepared a plan to avoid this problem to happen again in the future.

---

With that being said, we restored the old URL, which is now **deprecated**.

```shell
⚡ curl https://javascript-minifier.com/raw -X POST -k --data-urlencode 'input=console.log(1);'
console.log(1);
```

We suggest to **migrate your code to the new URL**:

```shell
⚡ curl https://www.toptal.com/developers/javascript-minifier/raw -X POST -k --data-urlencode 'input=console.log(2);'
console.log(2);
```

Thank you.

**Comment by promatik** [comment]
Hi @jodosha, I've just updated to the new URL.
Thank you!
